/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.rath.umbra;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP_ASL = 6;
  /** RegularExpression Id. */
  int OP_ASR = 7;
  /** RegularExpression Id. */
  int OP_LTE = 8;
  /** RegularExpression Id. */
  int OP_GTE = 9;
  /** RegularExpression Id. */
  int OP_LSL = 10;
  /** RegularExpression Id. */
  int OP_LSR = 11;
  /** RegularExpression Id. */
  int OP_EXCL = 12;
  /** RegularExpression Id. */
  int OP_PLUS = 13;
  /** RegularExpression Id. */
  int OP_HYPHEN = 14;
  /** RegularExpression Id. */
  int OP_ASTER = 15;
  /** RegularExpression Id. */
  int OP_EQUAL = 16;
  /** RegularExpression Id. */
  int OP_SLASH = 17;
  /** RegularExpression Id. */
  int OP_PERCENT = 18;
  /** RegularExpression Id. */
  int OP_CARET = 19;
  /** RegularExpression Id. */
  int OP_GT = 20;
  /** RegularExpression Id. */
  int OP_LT = 21;
  /** RegularExpression Id. */
  int SEP_LPAREN = 22;
  /** RegularExpression Id. */
  int SEP_RPAREN = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 44;
  /** RegularExpression Id. */
  int REFERENCE = 45;
  /** RegularExpression Id. */
  int LIT_GENERAL = 46;
  /** RegularExpression Id. */
  int LIT_NUMBER = 47;
  /** RegularExpression Id. */
  int LIT_DECIMAL = 48;
  /** RegularExpression Id. */
  int LIT_HEX = 49;
  /** RegularExpression Id. */
  int LIT_CHAR = 50;
  /** RegularExpression Id. */
  int LIT_STRING = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"<<<\"",
    "\">>>\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"\\\"\"",
    "\"@\"",
    "\".\"",
    "\"var\"",
    "\"set\"",
    "\"param\"",
    "\"if\"",
    "\"else\"",
    "\"main\"",
    "\"func\"",
    "\"for\"",
    "\"return\"",
    "\"while\"",
    "<IDENTIFIER>",
    "<REFERENCE>",
    "<LIT_GENERAL>",
    "<LIT_NUMBER>",
    "<LIT_DECIMAL>",
    "<LIT_HEX>",
    "<LIT_CHAR>",
    "<LIT_STRING>",
  };

}
